sudo: required

language: generic

services:
  - docker

before_install:
  - docker build -t jeantsai/phoenix-alpine ./docker

deploy:
  provider: script
  script: bash docker_push.sh
  on:
    branch: master
    