version: '3'

services:
  postgres:
    image: postgres:10-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: M0bi1e
    volumes:
      - ./db/pg-data:/var/lib/postgresql/data
  phx:
    build: ./docker/alpine-phoenix-preview
    image: alpine-phoenix-preview
    ports:
      - 4100:4000
    volumes:
      - .:/app
    links:
      - postgres
    entrypoint:
      - sh
    stdin_open: true
    tty: true